name: Debug
on:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Script
        env:
         RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          java -version
          javac -version
          echo "$RCLONE_CONFIG" > ./rclone.conf
          bash script.sh
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
